### ISSUE TITLE
Time to release new package to PyPI?

### ISSUE THREAD

**Issue by travenin** [Amsterdam/django-gisserver#10]
Current latest version in PyPI is 1.1.3, published May 2021 https://pypi.org/project/django-gisserver/

Since that there have been some commits, but no active development.

Would it be great to publish the current version to PyPI? Assuming that the current version is acceptable for a release.

PS: Greetings from City of Helsinki

**Comment by vdboor** [comment]
@travenin version 1.2 has just been released. It took more effort then expected, and gave a lot of extra features (M2M support, ArrayField support, etc..) and performance improvements.
