### ISSUE TITLE
Is it necessary Geoserver or QGIS to use this server?

### ISSUE THREAD

**Issue by aguilarpablo** [Amsterdam/django-gisserver#13]
Hi, this is just a question. I don't quite understand if it is necessary to make requests to a provider like Geoserver, or with this functionality you can get what you need from postgis. Thanks for your approach!

**Comment by webgisman** [comment]
no there is no need. you can do everything with python libraries with less performance with servers built on c sharp or java at least

**Comment by aguilarpablo** [comment]
ok nice, so in the getting started what does the provider and xml_namespace in the documentation refer to? I understand that it will make the connection to the database with the django configuration that we set up.

**Comment by vdboor** [comment]
Hi @aguilarpablo! This is a stand-alone server, which clients can connect to.

The fields for the `ServiceDescription` object provide metadata for anyone that uses your server. You should fill in your contact details there, so when people use your server, they know who provided that service to them.
