### ISSUE TITLE
Failing to add layer to ArcGIS

### ISSUE THREAD

**Issue by giovannicimolin** [Amsterdam/django-gisserver#15]
Did anyone bump into this issue before? I'm trying to use this to integrate with ArcGIS, but I always get an error like this:
```
The WFS service, URL, can't be added to the map. It's either not available or you have entered an invalid URL for the type of layer you want to reference.
```
When looking at the requests, I see that ArcGIS tries to access WFS `1.0.0`, `1.1.0` and `2.0.0` before displaying the error message (only the `2.0.0` request succeeds). 
Is there any way to force ArcGIS to only use the 2.0.0 version? Did anyone run into a similar issue?

Btw, this works perfectly on QGIS, but refuses to work on ArcGIS.

**Comment by jjmurre** [comment]
Hi, we ran into the same issues with ArcGIS online. We contacted ESRI. They told us that this is a problem with ArcGIS online. However, by default ArcGIS online start with the classic map view. It is possible to switch to a new type of mapviewer (at the top right of the screen). This new mapviewer can work with the WFS from django-gisserver.

**Comment by giovannicimolin** [comment]
@jjmurre Oh, you're right! It works only if added directly in the map using this option:
![image](https://user-images.githubusercontent.com/27893385/197242975-258fd3b7-3133-4d4b-8dc2-c709725af55b.png)

Thanks for the pointer! 

I also want to note that trying to add this to the `Content` doesn't work and fails with the same error.
