### ISSUE TITLE
Exposing complex fields

### ISSUE THREAD

**Issue by robertpoziumschi** [Amsterdam/django-gisserver#9]
Hi guys,

Is there any way to expose fields like ImageField (the url) or ManyToManyField (list of ids)?

I tried the following for ImageField but it didn't work:
- subclassed ImageField class and overridden value_from_object to return the ImageField.url field
- created a property (in the model that contains the ImageField) which returns the ImageField.url field

Thank you,
Robert

**Comment by vdboor** [comment]
Hi @robertpoziumschi

It seems you've touched a unpolished spot there. We're currently not using `value_from_object()`, only `getattr(model_instance, fieldname)`. I'm not that familiar with `value_from_object()`, should that be the preferred route?

Fortunately, the current field structure does allow you to override attribute retrieval.

```
from gisserver.features import FeatureField
from gisserer.types import XsdElement

class XsdImageElement(XsdElement):
    def get_value(self, instance):
        return getattr(instance, self.model_attribute)

class FeatureImageField(FeatureField):
    xsd_element_class = XsdImageElement
```

Then you can use the `FeatureImageField` in the `FeatureType` definition directly.

```
feature = FeatureType(
    fields=[
       "id",
       "name",
       FeatureImageField("image"),
    ]
)
```

Seeing the complexity, I do think we should provide some shortcuts to simplify this.

**Comment by vdboor** [comment]
I've added 2 fixes in the master branch:

* No longer needing to override `FeatureField` too: 915da46dbd35009d825e6a29a1b7b3ec91a6888c
* The code now reads `value_from_object()`: 4e5084a1a79c681d3468745e95388babccbc04a0

So the example above becomes:

```
class XsdImageElement(XsdElement):
    def get_value(self, instance):
        return self.source.object_from_object(instance)

feature = FeatureType(
    fields=[
       "id",
       "name",
       field("image", xsd_class=XsdImageElement),
    ]
)
```

**Comment by robertpoziumschi** [comment]
Thank you very much!

**Comment by vdboor** [comment]
@robertpoziumschi FYI, version 1.2 has just been released with M2M field support too.
